## -------- Define Titles -------- ##
ROOT_TITLE = "HKU POTATO"


## -------- Define Colors -------- ##

ROOT_BG_COLOR = "#EAEEF1"
SIDE_BAR_BG_COLOR = "#282B3D"
CAMERA_BG_COLOR = "#141729"
WARNING_FG_COLOR = "#E76A5A"
BOX_BG_COLOR = '#FFFFFF'
SETTING_TEXT_HOVER_FG_COLOR = "#73B9F8"
SETTING_TEXT_NORMAL_FG_COLOR = "#2091F6"
PALE_GRAY = "#C2C2C2"
TIMETABLE_HIGHLIGHT_COLOR = "#F5F5FE"

## suppose at most 10 courses will be displayed

TIMETABLE_BG_1_COLOR = "#1395FF"
TIMETABLE_BG_2_COLOR = "#AFD909"
TIMETABLE_BG_3_COLOR = "#FC3A70"
TIMETABLE_BG_4_COLOR = "#FDAE2E"
TIMETABLE_BG_5_COLOR = "#8B3FFF"

TIMETABLE_BG_6_COLOR = "#18B38D"
TIMETABLE_BG_7_COLOR = "#E9A6B7"
TIMETABLE_BG_8_COLOR = "#FD772E"
TIMETABLE_BG_9_COLOR = "#ff4040"
TIMETABLE_BG_10_COLOR = "#D280FC"

TIMETABLE_BG_COLORS = [TIMETABLE_BG_1_COLOR,
                       TIMETABLE_BG_2_COLOR,
                       TIMETABLE_BG_3_COLOR,
                       TIMETABLE_BG_4_COLOR,
                       TIMETABLE_BG_5_COLOR,
                       TIMETABLE_BG_6_COLOR,
                       TIMETABLE_BG_7_COLOR,
                       TIMETABLE_BG_8_COLOR,
                       TIMETABLE_BG_9_COLOR,
                       TIMETABLE_BG_10_COLOR]
